"""
Clinical Guideline Agent.

Provides evidence-based clinical guideline recommendations.
"""

from typing import Any, Dict, List, Optional
from medagentx.agents.base_template import SpecializedAgent
from medagentx.core.types import (
    AgentConfig,
    RecommendationType,
)


class ClinicalGuidelineAgent(SpecializedAgent):
    """
    Agent specialized in clinical guidelines.
    
    Capabilities:
    - Retrieve relevant clinical guidelines
    - Apply guidelines to specific cases
    - Provide evidence-based recommendations
    - Guideline compliance checking
    """
    
    def __init__(
        self,
        config: AgentConfig,
        tool_registry: Optional[Any] = None,
        governance_engine: Optional[Any] = None,
        knowledge_base: Optional[Any] = None,
    ):
        """Initialize Clinical Guideline Agent."""
        if config.description == "":
            config.description = (
                "Provides evidence-based clinical guideline recommendations. "
                "Retrieves and applies relevant guidelines to patient cases."
            )
        super().__init__(config, tool_registry, governance_engine, knowledge_base)
    
    async def get_guideline_recommendations(
        self,
        condition: str,
        patient_data: Dict[str, Any],
        guideline_source: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Get clinical guideline recommendations for a condition.
        
        Args:
            condition: Condition or diagnosis
            patient_data: Patient clinical data
            guideline_source: Specific guideline source (e.g., "NICE", "AHA")
            
        Returns:
            Guideline recommendations
        """
        task = f"""
        Retrieve and apply clinical guidelines:
        - Condition: {condition}
        - Patient Data: {patient_data}
        - Guideline Source: {guideline_source or "All"}
        
        Steps:
        1. Identify relevant clinical guidelines
        2. Retrieve guideline content
        3. Apply guidelines to patient case
        4. Generate evidence-based recommendations
        5. Check guideline compliance
        """
        
        state = await self.execute(task, context={
            "condition": condition,
            "patient_data": patient_data,
            "guideline_source": guideline_source,
        })
        
        query = f"clinical guidelines {condition}"
        knowledge = await self.retrieve_clinical_knowledge(query, top_k=10)
        
        confidence = await self.assess_confidence(
            evidence=[item.get("content", "") for item in knowledge],
            quality_indicators={"high_quality_source": True, "multiple_sources": len(knowledge) > 5},
        )
        
        recommendation = await self.generate_recommendation(
            recommendation_type=RecommendationType.TREATMENT_SUGGESTION,
            content=f"Clinical guideline recommendations for {condition}: [Generated by agent]",
            confidence_score=confidence,
            supporting_evidence=[item.get("content", "")[:200] for item in knowledge[:5]],
            risks_and_warnings=[
                "Guidelines are recommendations, not mandates.",
                "Clinical judgment should always override guidelines when appropriate.",
            ],
        )
        
        return {
            "state": state,
            "recommendation": recommendation,
            "guidelines_applied": [],
        }

