"""
Diagnosis Support Agent.

Provides differential diagnosis support and diagnostic reasoning assistance.
"""

from typing import Any, Dict, List, Optional
from medagentx.agents.base_template import SpecializedAgent
from medagentx.core.types import (
    AgentConfig,
    RecommendationType,
)


class DiagnosisSupportAgent(SpecializedAgent):
    """
    Agent specialized in providing differential diagnosis support.
    
    Capabilities:
    - Generate differential diagnosis lists
    - Rank conditions by likelihood
    - Suggest additional diagnostic tests
    - Provide clinical reasoning support
    """
    
    def __init__(
        self,
        config: AgentConfig,
        tool_registry: Optional[Any] = None,
        governance_engine: Optional[Any] = None,
        knowledge_base: Optional[Any] = None,
    ):
        """Initialize Diagnosis Support Agent."""
        if config.description == "":
            config.description = (
                "Provides differential diagnosis support and diagnostic reasoning. "
                "Generates ranked lists of possible conditions with supporting evidence."
            )
        super().__init__(config, tool_registry, governance_engine, knowledge_base)
    
    async def generate_differential_diagnosis(
        self,
        symptoms: str,
        patient_data: Dict[str, Any],
        existing_tests: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Generate a differential diagnosis.
        
        Args:
            symptoms: Symptom description
            patient_data: Patient clinical data
            existing_tests: Already performed tests
            
        Returns:
            Differential diagnosis with ranked conditions
        """
        task = f"""
        Generate a differential diagnosis based on:
        - Symptoms: {symptoms}
        - Patient Data: {patient_data}
        - Existing Tests: {existing_tests or []}
        
        Steps:
        1. Analyze symptom patterns
        2. Consider patient demographics and history
        3. Retrieve relevant diagnostic guidelines
        4. Generate ranked list of possible conditions
        5. Suggest additional diagnostic tests
        6. Provide clinical reasoning
        """
        
        state = await self.execute(task, context={"symptoms": symptoms, "patient_data": patient_data})
        
        # Retrieve diagnostic knowledge
        query = f"{symptoms} differential diagnosis"
        knowledge = await self.retrieve_clinical_knowledge(query, top_k=10)
        
        confidence = await self.assess_confidence(
            evidence=[item.get("content", "") for item in knowledge],
            quality_indicators={"multiple_sources": len(knowledge) > 5},
        )
        
        recommendation = await self.generate_recommendation(
            recommendation_type=RecommendationType.DIFFERENTIAL_DIAGNOSIS,
            content="Differential diagnosis with ranked conditions: [Generated by agent]",
            confidence_score=confidence,
            supporting_evidence=[item.get("content", "")[:200] for item in knowledge[:5]],
            risks_and_warnings=[
                "This is decision support only. Final diagnosis requires physician judgment.",
                "Consider all possibilities, not just the top-ranked conditions.",
            ],
        )
        
        return {
            "state": state,
            "recommendation": recommendation,
            "differential_diagnosis": "Ranked list of conditions",  # Would be populated by LLM
        }

