"""
Medical Coder Agent.

Specialized in medical coding (ICD-10, CPT, HCPCS) and billing support.
"""

from typing import Any, Dict, List, Optional
from medagentx.agents.base_template import SpecializedAgent
from medagentx.core.types import (
    AgentConfig,
    RecommendationType,
)


class MedicalCoderAgent(SpecializedAgent):
    """
    Agent specialized in medical coding.
    
    Capabilities:
    - ICD-10 diagnosis coding
    - CPT procedure coding
    - HCPCS code suggestions
    - Coding compliance checks
    - Billing optimization
    """
    
    def __init__(
        self,
        config: AgentConfig,
        tool_registry: Optional[Any] = None,
        governance_engine: Optional[Any] = None,
        knowledge_base: Optional[Any] = None,
    ):
        """Initialize Medical Coder Agent."""
        if config.description == "":
            config.description = (
                "Provides medical coding support for ICD-10, CPT, and HCPCS codes. "
                "Ensures coding accuracy and compliance."
            )
        super().__init__(config, tool_registry, governance_engine, knowledge_base)
    
    async def suggest_codes(
        self,
        diagnosis: str,
        procedures: Optional[List[str]] = None,
        patient_data: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Suggest medical codes for diagnosis and procedures.
        
        Args:
            diagnosis: Diagnosis description
            procedures: List of procedures performed
            patient_data: Additional patient context
            
        Returns:
            Coding suggestions with ICD-10, CPT, HCPCS codes
        """
        task = f"""
        Suggest medical codes for:
        - Diagnosis: {diagnosis}
        - Procedures: {procedures or []}
        - Patient Data: {patient_data or {}}
        
        Steps:
        1. Identify relevant ICD-10 codes for diagnosis
        2. Identify relevant CPT codes for procedures
        3. Suggest HCPCS codes if applicable
        4. Verify code accuracy and specificity
        5. Check for coding compliance issues
        6. Provide coding recommendations
        """
        
        state = await self.execute(task, context={
            "diagnosis": diagnosis,
            "procedures": procedures,
            "patient_data": patient_data,
        })
        
        # Retrieve coding knowledge
        query = f"ICD-10 {diagnosis} CPT {procedures}"
        knowledge = await self.retrieve_clinical_knowledge(query, top_k=5)
        
        confidence = await self.assess_confidence(
            evidence=[item.get("content", "") for item in knowledge],
            quality_indicators={"high_quality_source": True},
        )
        
        recommendation = await self.generate_recommendation(
            recommendation_type=RecommendationType.CODING_SUGGESTION,
            content=f"Coding suggestions for diagnosis and procedures: [Generated by agent]",
            confidence_score=confidence,
            supporting_evidence=[item.get("content", "")[:200] for item in knowledge],
            risks_and_warnings=[
                "Verify codes against official coding guidelines.",
                "Ensure specificity requirements are met.",
                "Review for compliance with payer requirements.",
            ],
        )
        
        return {
            "state": state,
            "recommendation": recommendation,
            "suggested_codes": {
                "icd10": [],
                "cpt": [],
                "hcpc": [],
            },
        }

