"""
Prescription Review Agent.

Reviews prescriptions for safety, interactions, and appropriateness.
"""

from typing import Any, Dict, List, Optional
from medagentx.agents.base_template import SpecializedAgent
from medagentx.core.types import (
    AgentConfig,
    RecommendationType,
)


class PrescriptionReviewAgent(SpecializedAgent):
    """
    Agent specialized in prescription review.
    
    Capabilities:
    - Drug-drug interaction checking
    - Drug-allergy checking
    - Dosage verification
    - Contraindication checking
    - Medication appropriateness review
    """
    
    def __init__(
        self,
        config: AgentConfig,
        tool_registry: Optional[Any] = None,
        governance_engine: Optional[Any] = None,
        knowledge_base: Optional[Any] = None,
    ):
        """Initialize Prescription Review Agent."""
        if config.description == "":
            config.description = (
                "Reviews prescriptions for safety, interactions, and appropriateness. "
                "Checks drug interactions, allergies, and contraindications."
            )
        super().__init__(config, tool_registry, governance_engine, knowledge_base)
    
    async def review_prescription(
        self,
        medications: List[Dict[str, Any]],
        patient_allergies: Optional[List[str]] = None,
        current_medications: Optional[List[str]] = None,
        patient_data: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Review prescription for safety and appropriateness.
        
        Args:
            medications: List of prescribed medications with dosages
            patient_allergies: Known patient allergies
            current_medications: Currently taking medications
            patient_data: Additional patient context
            
        Returns:
            Review results with warnings and recommendations
        """
        task = f"""
        Review prescription for safety:
        - New Medications: {medications}
        - Allergies: {patient_allergies or []}
        - Current Medications: {current_medications or []}
        - Patient Data: {patient_data or {}}
        
        Steps:
        1. Check for drug-drug interactions
        2. Check for drug-allergy interactions
        3. Verify dosage appropriateness
        4. Check contraindications
        5. Review medication appropriateness
        6. Generate safety warnings
        """
        
        state = await self.execute(task, context={
            "medications": medications,
            "allergies": patient_allergies,
            "current_medications": current_medications,
            "patient_data": patient_data,
        })
        
        # Retrieve drug interaction knowledge
        med_names = [m.get("name", "") for m in medications]
        query = f"drug interactions {', '.join(med_names)}"
        knowledge = await self.retrieve_clinical_knowledge(query, top_k=5)
        
        confidence = await self.assess_confidence(
            evidence=[item.get("content", "") for item in knowledge],
            quality_indicators={"high_quality_source": True},
        )
        
        recommendation = await self.generate_recommendation(
            recommendation_type=RecommendationType.MEDICATION_REVIEW,
            content="Prescription review results: [Generated by agent]",
            confidence_score=confidence,
            supporting_evidence=[item.get("content", "")[:200] for item in knowledge],
            risks_and_warnings=[
                "Review all interactions and warnings carefully.",
                "Verify dosages against patient-specific factors.",
                "Consider alternative medications if concerns identified.",
            ],
        )
        
        return {
            "state": state,
            "recommendation": recommendation,
            "review_summary": "Prescription review complete",
            "warnings": [],
            "interactions": [],
        }

