"""
Symptom Analyzer Agent.

Analyzes patient symptoms and generates initial hypotheses about
possible conditions.
"""

from typing import Any, Dict, List, Optional
from medagentx.agents.base_template import SpecializedAgent
from medagentx.core.types import (
    AgentConfig,
    RecommendationType,
    ClinicalConfidence,
)


class SymptomAnalyzerAgent(SpecializedAgent):
    """
    Agent specialized in analyzing symptoms and generating diagnostic hypotheses.
    
    Capabilities:
    - Parse and structure symptom descriptions
    - Generate possible condition hypotheses
    - Retrieve relevant clinical knowledge
    - Assess symptom severity and urgency
    """
    
    def __init__(
        self,
        config: AgentConfig,
        tool_registry: Optional[Any] = None,
        governance_engine: Optional[Any] = None,
        knowledge_base: Optional[Any] = None,
    ):
        """Initialize Symptom Analyzer Agent."""
        if config.description == "":
            config.description = (
                "Analyzes patient symptoms and generates initial diagnostic hypotheses. "
                "Provides structured symptom analysis and condition suggestions."
            )
        super().__init__(config, tool_registry, governance_engine, knowledge_base)
    
    async def analyze_symptoms(
        self,
        symptoms: str,
        patient_context: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Analyze symptoms and generate hypotheses.
        
        Args:
            symptoms: Symptom description (free text or structured)
            patient_context: Additional patient context (age, gender, history, etc.)
            
        Returns:
            Analysis results with hypotheses
        """
        # Structure the task
        task = f"""
        Analyze the following symptoms and generate diagnostic hypotheses:
        
        Symptoms: {symptoms}
        Patient Context: {patient_context or {}}
        
        Steps:
        1. Parse and structure the symptom description
        2. Identify key symptom patterns
        3. Retrieve relevant clinical knowledge
        4. Generate possible condition hypotheses
        5. Assess urgency and severity
        6. Provide structured recommendations
        """
        
        # Execute the agent
        state = await self.execute(task, context={"symptoms": symptoms, "patient_context": patient_context})
        
        # Retrieve relevant knowledge
        knowledge = await self.retrieve_clinical_knowledge(symptoms, top_k=5)
        
        # Generate recommendation
        confidence = await self.assess_confidence(
            evidence=[item.get("content", "") for item in knowledge],
            quality_indicators={"high_quality_source": True, "multiple_sources": len(knowledge) > 2},
        )
        
        recommendation = await self.generate_recommendation(
            recommendation_type=RecommendationType.DIAGNOSIS_HYPOTHESIS,
            content=f"Based on symptom analysis, possible conditions include: [Generated by agent]",
            confidence_score=confidence,
            supporting_evidence=[item.get("content", "")[:200] for item in knowledge[:3]],
            risks_and_warnings=[
                "This is a preliminary hypothesis. Full diagnostic workup required.",
                "Human physician review mandatory before any treatment decisions.",
            ],
        )
        
        return {
            "state": state,
            "recommendation": recommendation,
            "knowledge_retrieved": len(knowledge),
        }

